// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu() {
  return window['go']['app']['App']['ApplicationMenu']();
}

export function ApplyUpdate() {
  return window['go']['app']['App']['ApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function DeleteLocalAccount(arg1) {
  return window['go']['app']['App']['DeleteLocalAccount'](arg1);
}

export function DeleteLocalCharacter(arg1) {
  return window['go']['app']['App']['DeleteLocalCharacter'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['app']['App']['DeleteSource'](arg1);
}

export function DiscoverP99LoginProxyInstalls() {
  return window['go']['app']['App']['DiscoverP99LoginProxyInstalls']();
}

export function ExportLocalAccountsCSV() {
  return window['go']['app']['App']['ExportLocalAccountsCSV']();
}

export function GetEqHostState() {
  return window['go']['app']['App']['GetEqHostState']();
}

export function GetLocalAccounts() {
  return window['go']['app']['App']['GetLocalAccounts']();
}

export function GetLocalCharacters() {
  return window['go']['app']['App']['GetLocalCharacters']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetSources() {
  return window['go']['app']['App']['GetSources']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function ImportLocalAccountsCSV() {
  return window['go']['app']['App']['ImportLocalAccountsCSV']();
}

export function ImportLocalAccountsFromPath(arg1) {
  return window['go']['app']['App']['ImportLocalAccountsFromPath'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenEQDirectory() {
  return window['go']['app']['App']['OpenEQDirectory']();
}

export function OpenFolderInFileManager(arg1) {
  return window['go']['app']['App']['OpenFolderInFileManager'](arg1);
}

export function OpenReleaseURL(arg1) {
  return window['go']['app']['App']['OpenReleaseURL'](arg1);
}

export function PickEQDirectory() {
  return window['go']['app']['App']['PickEQDirectory']();
}

export function PickLocalAccountsCSVFile() {
  return window['go']['app']['App']['PickLocalAccountsCSVFile']();
}

export function PickP99ProxyConfigFile(arg1) {
  return window['go']['app']['App']['PickP99ProxyConfigFile'](arg1);
}

export function PickP99ProxyDataDirectory(arg1) {
  return window['go']['app']['App']['PickP99ProxyDataDirectory'](arg1);
}

export function PreviewSourceJSON(arg1) {
  return window['go']['app']['App']['PreviewSourceJSON'](arg1);
}

export function RestoreEqHostBackup() {
  return window['go']['app']['App']['RestoreEqHostBackup']();
}

export function SSOAdminAddAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['SSOAdminAddAccount'](arg1, arg2, arg3);
}

export function SSOAdminAddAlias(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminAddAlias'](arg1, arg2);
}

export function SSOAdminAddCharacter(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminAddCharacter'](arg1, arg2);
}

export function SSOAdminAddTag(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminAddTag'](arg1, arg2);
}

export function SSOAdminRemoveAccount(arg1) {
  return window['go']['app']['App']['SSOAdminRemoveAccount'](arg1);
}

export function SSOAdminRemoveAlias(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminRemoveAlias'](arg1, arg2);
}

export function SSOAdminRemoveCharacter(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminRemoveCharacter'](arg1, arg2);
}

export function SSOAdminRemoveTag(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminRemoveTag'](arg1, arg2);
}

export function SSOAdminSetUserAccess(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminSetUserAccess'](arg1, arg2);
}

export function SSOAdminSetUserRoles(arg1, arg2) {
  return window['go']['app']['App']['SSOAdminSetUserRoles'](arg1, arg2);
}

export function SSOAdminUpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SSOAdminUpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveEqHostContent(arg1) {
  return window['go']['app']['App']['SaveEqHostContent'](arg1);
}

export function SaveLocalAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveLocalAccount'](arg1, arg2, arg3);
}

export function SaveLocalCharacter(arg1, arg2) {
  return window['go']['app']['App']['SaveLocalCharacter'](arg1, arg2);
}

export function SaveSource(arg1) {
  return window['go']['app']['App']['SaveSource'](arg1);
}

export function ScanP99LoginProxyInstalls() {
  return window['go']['app']['App']['ScanP99LoginProxyInstalls']();
}

export function SetActiveSource(arg1) {
  return window['go']['app']['App']['SetActiveSource'](arg1);
}

export function SetConnectionMode(arg1) {
  return window['go']['app']['App']['SetConnectionMode'](arg1);
}

export function SetEQDirectory(arg1) {
  return window['go']['app']['App']['SetEQDirectory'](arg1);
}

export function SetListenAddr(arg1) {
  return window['go']['app']['App']['SetListenAddr'](arg1);
}

export function SetListenPort(arg1) {
  return window['go']['app']['App']['SetListenPort'](arg1);
}

export function SetProxyEnabled(arg1) {
  return window['go']['app']['App']['SetProxyEnabled'](arg1);
}

export function ShareLocalAccount(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ShareLocalAccount'](arg1, arg2, arg3, arg4);
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function UnshareLocalAccount(arg1) {
  return window['go']['app']['App']['UnshareLocalAccount'](arg1);
}
