// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {app} from '../models';
import {logbuf} from '../models';
import {options} from '../models';
import {sources} from '../models';

export function ApplicationMenu():Promise<menu.Menu>;

export function CheckUpdate():Promise<app.UpdateInfo>;

export function ClearLogs():Promise<void>;

export function DeleteLocalAccount(arg1:string):Promise<void>;

export function DeleteLocalCharacter(arg1:string):Promise<void>;

export function DeleteSource(arg1:string):Promise<void>;

export function DiscoverP99LoginProxyInstalls():Promise<Array<app.P99ProxyInstallDTO>>;

export function ExportLocalAccountsCSV():Promise<string>;

export function GetEqHostState():Promise<app.EqHostState>;

export function GetLocalAccounts():Promise<Array<app.LocalAccountDTO>>;

export function GetLocalCharacters():Promise<Array<app.LocalCharacterDTO>>;

export function GetLogs(arg1:number):Promise<Array<logbuf.Entry>>;

export function GetSources():Promise<Array<app.SourceDTO>>;

export function GetStatus():Promise<app.StatusDTO>;

export function GetVersion():Promise<string>;

export function ImportLocalAccountsCSV():Promise<string>;

export function ImportLocalAccountsFromPath(arg1:string):Promise<app.ImportAccountsResult>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenEQDirectory():Promise<void>;

export function OpenFolderInFileManager(arg1:string):Promise<void>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PickEQDirectory():Promise<string>;

export function PickLocalAccountsCSVFile():Promise<string>;

export function PickP99ProxyConfigFile(arg1:string):Promise<string>;

export function PickP99ProxyDataDirectory(arg1:string):Promise<string>;

export function PreviewSourceJSON(arg1:string):Promise<Array<app.SourceImportPreview>>;

export function RestoreEqHostBackup():Promise<void>;

export function SSOAdminAddAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSOAdminAddAlias(arg1:string,arg2:number):Promise<void>;

export function SSOAdminAddCharacter(arg1:string,arg2:number):Promise<void>;

export function SSOAdminAddTag(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveAccount(arg1:number):Promise<void>;

export function SSOAdminRemoveAlias(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveCharacter(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveTag(arg1:string,arg2:number):Promise<void>;

export function SSOAdminSetUserAccess(arg1:number,arg2:boolean):Promise<void>;

export function SSOAdminSetUserRoles(arg1:number,arg2:Array<string>):Promise<void>;

export function SSOAdminUpdateAccount(arg1:number,arg2:string,arg3:boolean,arg4:boolean,arg5:string,arg6:boolean):Promise<void>;

export function SaveEqHostContent(arg1:string):Promise<void>;

export function SaveLocalAccount(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveLocalCharacter(arg1:string,arg2:string):Promise<void>;

export function SaveSource(arg1:sources.Source):Promise<app.SourceDTO>;

export function ScanP99LoginProxyInstalls():Promise<Array<app.P99ProxyInstallDTO>>;

export function SetActiveSource(arg1:string):Promise<void>;

export function SetConnectionMode(arg1:string):Promise<void>;

export function SetEQDirectory(arg1:string):Promise<void>;

export function SetListenAddr(arg1:string):Promise<void>;

export function SetListenPort(arg1:number):Promise<void>;

export function SetProxyEnabled(arg1:boolean):Promise<void>;

export function ShareLocalAccount(arg1:string,arg2:Array<number>,arg3:Array<string>,arg4:Array<number>):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UnshareLocalAccount(arg1:string):Promise<void>;
