// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteLocalAccount(arg1) {
  return window['go']['main']['App']['DeleteLocalAccount'](arg1);
}

export function DeleteLocalCharacter(arg1) {
  return window['go']['main']['App']['DeleteLocalCharacter'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function ExportLocalAccountsCSV() {
  return window['go']['main']['App']['ExportLocalAccountsCSV']();
}

export function GetEqHostState() {
  return window['go']['main']['App']['GetEqHostState']();
}

export function GetLocalAccounts() {
  return window['go']['main']['App']['GetLocalAccounts']();
}

export function GetLocalCharacters() {
  return window['go']['main']['App']['GetLocalCharacters']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportLocalAccountsCSV() {
  return window['go']['main']['App']['ImportLocalAccountsCSV']();
}

export function OpenEQDirectory() {
  return window['go']['main']['App']['OpenEQDirectory']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function PickEQDirectory() {
  return window['go']['main']['App']['PickEQDirectory']();
}

export function PreviewSourceJSON(arg1) {
  return window['go']['main']['App']['PreviewSourceJSON'](arg1);
}

export function SSOAdminAddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSOAdminAddAccount'](arg1, arg2, arg3);
}

export function SSOAdminAddAlias(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminAddAlias'](arg1, arg2);
}

export function SSOAdminAddCharacter(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminAddCharacter'](arg1, arg2);
}

export function SSOAdminAddTag(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminAddTag'](arg1, arg2);
}

export function SSOAdminRemoveAccount(arg1) {
  return window['go']['main']['App']['SSOAdminRemoveAccount'](arg1);
}

export function SSOAdminRemoveAlias(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminRemoveAlias'](arg1, arg2);
}

export function SSOAdminRemoveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminRemoveCharacter'](arg1, arg2);
}

export function SSOAdminRemoveTag(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminRemoveTag'](arg1, arg2);
}

export function SSOAdminSetUserAccess(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminSetUserAccess'](arg1, arg2);
}

export function SSOAdminSetUserRoles(arg1, arg2) {
  return window['go']['main']['App']['SSOAdminSetUserRoles'](arg1, arg2);
}

export function SSOAdminUpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SSOAdminUpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RestoreEqHostBackup() {
  return window['go']['main']['App']['RestoreEqHostBackup']();
}

export function SaveEqHostContent(arg1) {
  return window['go']['main']['App']['SaveEqHostContent'](arg1);
}

export function SaveLocalAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLocalAccount'](arg1, arg2, arg3);
}

export function SaveLocalCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveLocalCharacter'](arg1, arg2);
}

export function SaveSource(arg1) {
  return window['go']['main']['App']['SaveSource'](arg1);
}

export function SetActiveSource(arg1) {
  return window['go']['main']['App']['SetActiveSource'](arg1);
}

export function SetConnectionMode(arg1) {
  return window['go']['main']['App']['SetConnectionMode'](arg1);
}

export function SetEQDirectory(arg1) {
  return window['go']['main']['App']['SetEQDirectory'](arg1);
}

export function SetListenAddr(arg1) {
  return window['go']['main']['App']['SetListenAddr'](arg1);
}

export function SetListenPort(arg1) {
  return window['go']['main']['App']['SetListenPort'](arg1);
}

export function SetProxyEnabled(arg1) {
  return window['go']['main']['App']['SetProxyEnabled'](arg1);
}

export function ShareLocalAccount(arg1, arg2) {
  return window['go']['main']['App']['ShareLocalAccount'](arg1, arg2);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UnshareLocalAccount(arg1) {
  return window['go']['main']['App']['UnshareLocalAccount'](arg1);
}
