// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sources} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function DeleteLocalAccount(arg1:string):Promise<void>;

export function DeleteLocalCharacter(arg1:string):Promise<void>;

export function DeleteSource(arg1:string):Promise<void>;

export function ExportLocalAccountsCSV():Promise<string>;

export function GetLocalAccounts():Promise<Array<main.LocalAccountDTO>>;

export function GetLocalCharacters():Promise<Array<main.LocalCharacterDTO>>;

export function GetSources():Promise<Array<main.SourceDTO>>;

export function GetStatus():Promise<main.StatusDTO>;

export function GetVersion():Promise<string>;

export function ImportLocalAccountsCSV():Promise<string>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PickEQDirectory():Promise<string>;

export function PreviewSourceURL(arg1:string):Promise<Array<main.SourceImportPreview>>;

export function SSOAdminAddAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSOAdminAddAlias(arg1:string,arg2:number):Promise<void>;

export function SSOAdminAddCharacter(arg1:string,arg2:number):Promise<void>;

export function SSOAdminAddTag(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveAccount(arg1:number):Promise<void>;

export function SSOAdminRemoveAlias(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveCharacter(arg1:string,arg2:number):Promise<void>;

export function SSOAdminRemoveTag(arg1:string,arg2:number):Promise<void>;

export function SSOAdminSetUserAccess(arg1:number,arg2:boolean):Promise<void>;

export function SSOAdminSetUserRoles(arg1:number,arg2:Array<string>):Promise<void>;

export function SSOAdminUpdateAccount(arg1:number,arg2:string,arg3:boolean,arg4:boolean,arg5:string,arg6:boolean):Promise<void>;

export function SaveLocalAccount(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveLocalCharacter(arg1:string,arg2:string):Promise<void>;

export function SaveSource(arg1:sources.Source):Promise<main.SourceDTO>;

export function SetActiveSource(arg1:string):Promise<void>;

export function SetConnectionMode(arg1:string):Promise<void>;

export function SetEQDirectory(arg1:string):Promise<void>;

export function SetListenAddr(arg1:string):Promise<void>;

export function SetListenPort(arg1:number):Promise<void>;

export function SetProxyEnabled(arg1:boolean):Promise<void>;

export function ShareLocalAccount(arg1:string,arg2:Array<number>):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UnshareLocalAccount(arg1:string):Promise<void>;
